server:
  port: 8083

spring:
  application:
    name: access-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:zyndex_access}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
